package com.banking.mini_banking.model.entity;

import java.math.BigDecimal;
import jakarta.persistence.*;
import lombok.*;

@Entity // This annotation specifies that the class is an entity and is mapped to a
        // database table.
@Table(name = "accounts") // This annotation specifies the name of the database table to be used for
                          // mapping. In this case, the table name is "accounts".
@Getter // This annotation generates getter methods for all fields in the class.
@Setter // This annotation generates setter methods for all fields in the class.
@NoArgsConstructor // This annotation generates a no-argument constructor for the class.
@AllArgsConstructor // This annotation generates a constructor with one parameter for each field in
                    // the class.
@Builder // This annotation provides a builder pattern implementation for the class,
         // allowing for more flexible and readable object creation.
public class Account {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // This annotation specifies that the primary key value will be
                                                        // automatically generated by the database. The strategy
                                                        // "IDENTITY" means that the database will handle the generation
                                                        // of unique IDs, typically using an auto-incrementing column.
    private Long id;

    @Column(name = "account_number", nullable = false, unique = true)
    private String accountNumber;

    @Column(nullable = false)
    private BigDecimal balance; // BigDecimal is used for monetary values to avoid issues with floating-point
                                // precision.

    @Column(nullable = false, length = 3)
    private String currency;

    @ManyToOne(fetch = FetchType.LAZY) // Many accounts can belong to one customer. FetchType.LAZY is used to avoid
                                       // loading the customer data unless it's explicitly accessed.
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;
}

// This class represents the Account entity in the mini banking application. It
// is annotated with JPA annotations to define how it maps to the database
// table. The class includes fields for the account number, balance, currency,
// and a reference to the associated customer. The account number is unique and
// cannot be null, while the balance and currency fields are also required. The
// relationship between Account and Customer is defined as many-to-one,
// indicating that multiple accounts can belong to a single customer. Lombok
// annotations are used to reduce boilerplate code by automatically generating
// getters, setters, constructors, and a builder pattern for the class.